name: Deploy AKS Cluster

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Bicep CLI
        uses: azure/setup-bicep@v0.3.9

      - name: Build Bicep template
        run: bicep build main.bicep --stdout > main.json

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy AKS cluster
        run: az deployment sub create --name "AKS-Deployment-$(date +%s)" --template-file main.json --parameters parameters.json
